### ISSUE TITLE
Replace Chiefdoms for Sierra Leone / Western

### ISSUE THREAD

**Issue by ni-ka** [eHealthAfrica/locations#27]
Apparently the Western Area has come up with a new structure for the chiefdoms (admin level 3 in SL):

Western Urban Chiefdoms:
Aberdeen 
Albert Academy
Allen Town I
Allen Town II
Ascension Town
Bombay
Bottom Oku
Brookfields
Brookfields-Congo
Brookfields-Red Pu
Cline Town
Cockerill-Aberdeen
Cockle-Bay / Colleg
Coconut Farm / Asho
Congo Town
Congo Water I
Congo Water II
Foulah Town
Fourah Bay
George Brook
Ginger Hall
Grass Field
Hill Station
Industrial Estate (Wellington)
Jalloh Terrace
Juba / Kaningo
Kingtom
Kissy Brook
Kissy Bye Pass I
Kissy Bye Pass II
Kissy Mental
Kissy Mess Mess
Kossoh Town
Kroo Town
Kuntolor
Lowcost Housing
Lumley
Magazine
Malama / Kamayama
Mamba Ridge I
Mamba Ridge II
Mayenkineh
Mount Aureol 
Mountain Regent 
Murray Town
New England - Hannes
New England - Hill C
Old Warf
Pamuronko
Pipelin / Wilkinson
Portee
Quarry
Robis
Rokupa
Sanders Brook
Shell
Sorie Town
Susan's Bay
Tasso Island
Tengbeh Town
Thunderhill
Tower Hill
Wilberforce

Western Rural Chiefdoms:
Koya - Fabaina Area
Koya - Madonkeh
Koya - Magbafti
Koya - Malambay
Koya - Newton
Koya - Songo
Mountain - Bathurst
Mountain - Charlotte
Mountain - Gloucester
Mountain - Leicester
Mountain - Regent
Other 
Waterloo - Benguema Village A
Waterloo - Campbell Town VIII
Waterloo - Hastings Village A
Waterloo - Waterloo Village A
York - Gbendembu 
York - Goderich - Adonkia/M
York - Goderich - Funkia
York - Hamilton
York - Kent
York - Sattia / Tombo
York - York 
Other

- [ ] location files should contain the new locations for Western Urban and Western Rural
- [ ] new locations should contain IDs that do not overlap with previous entries to prevent data mess

**Comment by ni-ka** [comment]
The call center stakeholders have agreed to use the updated locations as well. Will create a ticket there.

**Comment by danse** [comment]
@ni-ka how will call centre software support old data referring to old locations?

**Comment by ni-ka** [comment]
That will be defined in the call center repo ticket.
Am 02.07.2015 10:49 schrieb "Francesco Occhipinti" <notifications@github.com
